{% set name = "acquifer-napari" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/acquifer-napari-{{ version }}.tar.gz
  sha256: 285380aab2cf19bd733d239ef2cce9edd8791df158cb280fee2ae000f11bc705

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - acquifer
    - napari
    - python >=3.7

test:
  imports:
    - acquifer_napari_plugin
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/acquifer/acquifer-napari
  summary: Loader plugin for napari, to load Acquifer Imaging Machine datasets in napari, using dask for efficient lazy data-loading.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - LauLauThom
